# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12onxkpfwMmVhtxrekvlIGi1XPifkwifC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("Coffee_Qlty.csv")

df.rename(columns = {'REC_ID':'rec_id', 'Species':'species', 'Continent.of.Origin':'continent_of_origin', 'Country.of.Origin' :'country_of_origin',
       'Harvest.Year':'harvest_year', 'Expiration':'expiration', 'Variety':'variety', 'Color':'color', 'Processing.Method':'processing_method',
       'Aroma':'aroma', 'Flavor':'flavor', 'Aftertaste':'aftertaste', 'Acidity':'acidity', 'Body':'body', 'Balance':'balance',
       'Uniformity':'uniformity', 'Clean.Cup':'clean_cup', 'Sweetness':'sweetness', 'Moisture':'moisture', 'Quakers':'quakers',
       'Category.One.Defects':'category_one_defects', 'Category.Two.Defects':'category_two_defects'},inplace = True)

df.columns

df.isnull().sum()

df.dropna(inplace = True)

df.duplicated()

df.drop_duplicates(inplace=True)

expiry_year = []
for i in df['expiration']:

  if int(i[1]) < 7:
    i = int('20'+ i[len(i)-2] + i[len(i)-1])
  elif int(i[0]) == 1 or int(i[1]) > 6 :
    i = int('20'+ i[len(i)-2] + i[len(i)-1])
  expiry_year.append(i)

df['expiry_year'] = expiry_year

df['expiry_duration'] = df['expiry_year']-df['harvest_year']

arabica_df = df[df['species']=='Arabica']

robusta_df = df[df['species']=='Robusta']
robusta_df

plt.scatter(robusta_df['country_of_origin'].unique(),robusta_df.groupby(['country_of_origin']).mean(numeric_only=True)['sweetness'])
ax = plt.gca()
ax.set_ylim([5, 11])
plt.show()

plt.scatter(robusta_df['country_of_origin'].unique(),robusta_df.groupby(['country_of_origin']).mean(numeric_only=True)['aroma'])
ax = plt.gca()
ax.set_ylim([5, 11])
plt.show()

plt.scatter(robusta_df['country_of_origin'].unique(),robusta_df.groupby(['country_of_origin']).mean(numeric_only=True)['expiry_duration'])
ax = plt.gca()
ax.set_ylim([0, 4])
plt.show()

plt.figure(figsize=(30, 15), dpi=180)
plt.scatter(arabica_df['country_of_origin'].unique(), arabica_df.groupby(['country_of_origin']).mean(numeric_only=True)['sweetness'])
ax = plt.gca()
ax.set_ylim([5, 11])
plt.show()

plt.figure(figsize=(30, 15), dpi=180)
plt.scatter(arabica_df['country_of_origin'].unique(), arabica_df.groupby(['country_of_origin']).mean(numeric_only=True)['aroma'])
ax = plt.gca()
ax.set_ylim([5, 11])
plt.show()

plt.figure(figsize=(30, 15), dpi=180)
plt.scatter(arabica_df['country_of_origin'].unique(), arabica_df.groupby(['country_of_origin']).mean(numeric_only=True)['expiry_duration'])
ax = plt.gca()
ax.set_ylim([0,3])
plt.show()
